{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "music-assistant-alexa-skill.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "music-assistant-alexa-skill.labels" . | nindent 4 }}
type: Opaque
data:
  APP_USERNAME: {{ .Values.credentials.appUsername | b64enc | quote }}
  APP_PASSWORD: {{ .Values.credentials.appPassword | b64enc | quote }}
{{- end }}
